### ISSUE TITLE
add stealer

### ISSUE THREAD

**Issue by Smug246** [opsec-bot/DMV#12]
i cba to add my stealer to the config but ur welcome to. https://github.com/Smug246/Luna-Token-Grabber

**Comment by Smug246** [comment]
> > i cba to add my stealer to the config but ur welcome to. https://github.com/Smug246/Luna-Token-Grabber
> 
> 
> 
> Check their discord (coo) before saying that.
> 
> Also, thats childish.

idc tbh. suck ur mum

**Comment by Blank-c** [comment]
Go do your dishes kid
